__author__ = [""]
__copyright__ = ""
__credits__ = [""]
__license__ = "MIT"
__version_num__ = [0, 4, 7] # Also change the version in pyproject.toml
__version__ = "{}.{}.{}".format(*__version_num__)
__maintainer__ = ""
__email__ = ""
__status__ = "Development"