# All settings can be overriden by environment variables with the same name and prefix OCAMONITOR_
# e.g. OCAMONITOR_NATS_HOST=test.oca.lan

#---------------------------default - controlroom---------------------

[default]  # global configuration is used by all environments, setting from here override all other settings
#window_size = [1900, 1040]
window_size = [1800, 1000]
panel_columns = [6,4,2]  # The size ratio of the columns in the panel grid
panel_rows = [5,1]   # The size ratio of the rows in the panel grid
style = "dark"
#style = "white"

nats_host = "nats.oca.lan"
nats_port = 4222

#log_level = "DEBUG"
log_level = "INFO"
#log_level = "WARNING"

# Panel page declaration:
# environment.panels.rowcolumn.tabname


[default.panels.00.Allsky]
#auto_interval = 10  # seconds, how long to show this page before auto switching to next page
source = "allsky_animation_mpl"  # page source - page is defined in oca_monitor/pages/example.py
vertical_screen = 0

[default.panels.00.Satellite]
#auto_interval = 10  # seconds, how long to show this page before auto switching to next page
source = "satellite_animation"  # page source - page is defined in oca_monitor/pages/example.py
vertical_screen = 0

[default.panels.01.Weather]
#auto_interval = 10  # seconds, how long to show this page before auto switching to next page
source = "wind"  # page source - page is defined in oca_monitor/pages/example.py
vertical_screen = 0

#[default.panels.01.Conditions]
#auto_interval = 10  # seconds, how long to show this page before auto switching to next page
#source = "conditions"  # page source - page is defined in oca_monitor/pages/example.py
#vertical_screen = 0

[default.panels.02.Control]
#auto_interval = 10  # seconds, how long to show this page before auto switching to next page
source = "tvs_controlroom"  # page source - page is defined in oca_monitor/pages/example.py

#[default.panels.02.Buttons]
#auto_interval = 10  # seconds, how long to show this page before auto switching to next page
#source = "buttons_controlroom"  # page source - page is defined in oca_monitor/pages/example.py

[default.panels.12.Message]
#auto_interval = 10  # seconds, how long to show this page before auto switching to next page
source = "message"  # page source - page is defined in oca_monitor/pages/example.py

[default.panels.10.Telescopes]
#auto_interval = 10  # seconds, how long to show this page before auto switching to next page
source = "telescopes"  # page source - page is defined in oca_monitor/pages/example.py

#[default.panels.11.Water]
#auto_interval = 10  # seconds, how long to show this page before auto switching to next page
#source = "water"  # page source - page is defined in oca_monitor/pages/example.py


##--------------------------touchpanel controlroom---------------

[touch_controlroom]  # global configuration is used by all environments, setting from here override all other settings
window_size = [1250, 740]
panel_columns = [1]  # The size ratio of the columns in the panel grid
panel_rows = [1]   # The size ratio of the rows in the panel grid
style = "dark"
#style = "white"

nats_host = "nats.oca.lan"
nats_port = 4222

#log_level = "DEBUG"
log_level = "INFO"
#log_level = "WARNING"

# Panel page declaration:
# environment.panels.rowcolumn.tabname

[touch_controlroom.panels.00.Buttons]
source = "touch_buttons"  # page source - page is defined in oca_monitor/pages/example.py

##--------------------------touchpanel bedroom---------------

[touch_wbedroom]  # global configuration is used by all environments, setting from here override all other settings
window_size = [1020, 530]
panel_columns = [1]  # The size ratio of the columns in the panel grid
panel_rows = [1]   # The size ratio of the rows in the panel grid
style = "dark"
#style = "white"

nats_host = "nats.oca.lan"
nats_port = 4222

#log_level = "DEBUG"
log_level = "INFO"
#log_level = "WARNING"

# Panel page declaration:
# environment.panels.rowcolumn.tabname

[touch_wbedroom.panels.00.Buttons]
source = "touch_buttons_wbedroom"  # page source - page is defined in oca_monitor/pages/example.py


##--------------------------screen kitchen---------------

[kitchen]  # global configuration is used by all environments, setting from here override all other settings
window_size = [1080, 1850]
panel_columns = [1]  # The size ratio of the columns in the panel grid
panel_rows = [7,4,1]   # The size ratio of the rows in the panel grid
style = "dark"
#style = "white"

nats_host = "nats.oca.lan"
nats_port = 4222

#log_level = "DEBUG"
log_level = "INFO"
#log_level = "WARNING"

# Panel page declaration:
# environment.panels.rowcolumn.tabname
[kitchen.panels.00.Allsky]
#auto_interval = 10  # seconds, how long to show this page before auto switching to next page
source = "allsky_animation"  # page source - page is defined in oca_monitor/pages/example.py
vertical_screen=1

[kitchen.panels.00.Satellite]
#auto_interval = 10  # seconds, how long to show this page before auto switching to next page
source = "satellite_animation"  # page source - page is defined in oca_monitor/pages/example.py
vertical_screen=1

[kitchen.panels.10.Weather]
#auto_interval = 10  # seconds, how long to show this page before auto switching to next page
source = "wind"  # page source - page is defined in oca_monitor/pages/example.py
vertical_screen = 1

[kitchen.panels.20.Buttons]
source = "buttons_kitchen"  # page source - page is defined in oca_monitor/pages/example.py


##--------------------------screens tvroom---------------

[tvroom]  # global configuration is used by all environments, setting from here override all other settings
window_size = [1080, 1850]
panel_columns = [1]  # The size ratio of the columns in the panel grid
panel_rows = [7,4,1]   # The size ratio of the rows in the panel grid
style = "dark"
#style = "white"

nats_host = "nats.oca.lan"
nats_port = 4222

#log_level = "DEBUG"
log_level = "INFO"
#log_level = "WARNING"

# Panel page declaration:
# environment.panels.rowcolumn.tabname
[tvroom.panels.00.Allsky]
#auto_interval = 10  # seconds, how long to show this page before auto switching to next page
source = "allsky_animation"  # page source - page is defined in oca_monitor/pages/example.py
vertical_screen=1

[tvroom.panels.00.Satellite]
#auto_interval = 10  # seconds, how long to show this page before auto switching to next page
source = "satellite_animation"  # page source - page is defined in oca_monitor/pages/example.py
vertical_screen=1

[tvroom.panels.10.Weather]
#auto_interval = 10  # seconds, how long to show this page before auto switching to next page
source = "wind"  # page source - page is defined in oca_monitor/pages/example.py
vertical_screen = 1

[tvroom.panels.20.Buttons]
source = "buttons_tvroom"  # page source - page is defined in oca_monitor/pages/example.py


#----------dev----------

[dev]  # set OCAMONITOR_ENV=dev env var to use this configuration
nats_host = "localhost"

[dev.panels.00.wind]
source = "wind"

[dev.panels.00.hohohoh]
source = "example"
example_parameter = "Ho Ho"

