# All settings can be overriden by environment variables with the same name and prefix OCAMONITOR_
# e.g. OCAMONITOR_NATS_HOST=test.oca.lan

#---------------------------default - controlroom---------------------

[default]  # global configuration is used by all environments, setting from here override all other settings
window_size = [1900, 1040]
#window_size = [1800, 1000]
panel_columns = [4,6,4]  # The size ratio of the columns in the panel grid
panel_rows = [5,1]   # The size ratio of the rows in the panel grid
style = "dark"
#style = "white"

nats_host = "nats.oca.lan"
nats_port = 4222

#log_level = "DEBUG"
log_level = "INFO"
#log_level = "WARNING"

# Panel page declaration:
# environment.panels.rowcolumn.tabname

[default.panels.00.wk06]
#auto_interval = 10  # seconds, how long to show this page before auto switching to next page
source = "wk06_ofp"  # page source - page is defined in oca_monitor/pages/example.py

[default.panels.00.zb08]
#auto_interval = 10  # seconds, how long to show this page before auto switching to next page
source = "zb08_ofp"  # page source - page is defined in oca_monitor/pages/example.py

[default.panels.00.jk15]
#auto_interval = 10  # seconds, how long to show this page before auto switching to next page
source = "jk15_ofp"  # page source - page is defined in oca_monitor/pages/example.py

[default.panels.10.Message]
#auto_interval = 10  # seconds, how long to show this page before auto switching to next page
source = "message"  # page source - page is defined in oca_monitor/pages/example.py

[default.panels.01.Allsky]
#auto_interval = 10  # seconds, how long to show this page before auto switching to next page
source = "allsky_animation_mpl"  # page source - page is defined in oca_monitor/pages/example.py
vertical_screen = 0

[default.panels.01.Satellite]
#auto_interval = 10  # seconds, how long to show this page before auto switching to next page
source = "satellite_animation"  # page source - page is defined in oca_monitor/pages/example.py
vertical_screen = 0

[default.panels.11.Telescopes]
#auto_interval = 10  # seconds, how long to show this page before auto switching to next page
source = "telescopes"  # page source - page is defined in oca_monitor/pages/example.py

[default.panels.02.Weather]
#auto_interval = 10  # seconds, how long to show this page before auto switching to next page
source = "weather"  # page source - page is defined in oca_monitor/pages/example.py
vertical_screen = 0

[default.panels.12.Ephemeris]
#auto_interval = 10  # seconds, how long to show this page before auto switching to next page
source = "ephemeris"  # page source - page is defined in oca_monitor/pages/example.py

[default.panels.12.Conditions]
#auto_interval = 10  # seconds, how long to show this page before auto switching to next page
source = "conditions"  # page source - page is defined in oca_monitor/pages/example.py
#vertical_screen = 0



##--------------------------touchpanel controlroom---------------

[touch_controlroom]  # global configuration is used by all environments, setting from here override all other settings
window_size = [1270, 740]
panel_columns = [1]  # The size ratio of the columns in the panel grid
panel_rows = [1]   # The size ratio of the rows in the panel grid
style = "dark"
#style = "white"

nats_host = "nats.oca.lan"
nats_port = 4222

#log_level = "DEBUG"
log_level = "INFO"
#log_level = "WARNING"

# Panel page declaration:
# environment.panels.rowcolumn.tabname

[touch_controlroom.panels.00.Buttons]
source = "touch_buttons"  # page source - page is defined in oca_monitor/pages/example.py
light='controlroom'

##--------------------------touchpanel west bedroom---------------

[touch_wbedroom]  # global configuration is used by all environments, setting from here override all other settings
window_size = [1020, 530]
panel_columns = [1]  # The size ratio of the columns in the panel grid
panel_rows = [1]   # The size ratio of the rows in the panel grid
style = "dark"
#style = "white"

nats_host = "nats.oca.lan"
nats_port = 4222

#log_level = "DEBUG"
log_level = "INFO"
#log_level = "WARNING"

# Panel page declaration:
# environment.panels.rowcolumn.tabname

[touch_wbedroom.panels.00.Buttons]
source = "touch_buttons_wbedroom"  # page source - page is defined in oca_monitor/pages/example.py
room = 'westbedroom'
temp_subject='telemetry.conditions.bedroom-west-tsensor'

#[touch_wbedroom.panels.00.cameras]
#source = "cameras"  # page source - page is defined in oca_monitor/pages/example.py



##--------------------------touchpanel east bedroom---------------

[touch_ebedroom]  # global configuration is used by all environments, setting from here override all other settings
window_size = [1020, 530]
panel_columns = [1]  # The size ratio of the columns in the panel grid
panel_rows = [1]   # The size ratio of the rows in the panel grid
style = "dark"
#style = "white"

nats_host = "nats.oca.lan"
nats_port = 4222

#log_level = "DEBUG"
log_level = "INFO"
#log_level = "WARNING"

# Panel page declaration:
# environment.panels.rowcolumn.tabname

[touch_ebedroom.panels.00.Buttons]
source = "touch_buttons_wbedroom"  # page source - page is defined in oca_monitor/pages/example.py
room = 'eastbedroom'
temp_subject='telemetry.conditions.bedroom-east-tsensor'

##--------------------------screen kitchen---------------

[kitchen]  # global configuration is used by all environments, setting from here override all other settings
window_size = [1080, 1850]
panel_columns = [1]  # The size ratio of the columns in the panel grid
panel_rows = [7,4,1]   # The size ratio of the rows in the panel grid
style = "dark"
#style = "white"

nats_host = "nats.oca.lan"
nats_port = 4222

#log_level = "DEBUG"
log_level = "INFO"
#log_level = "WARNING"

# Panel page declaration:
# environment.panels.rowcolumn.tabname
[kitchen.panels.00.Allsky]
#auto_interval = 10  # seconds, how long to show this page before auto switching to next page
source = "allsky_animation"  # page source - page is defined in oca_monitor/pages/example.py
vertical_screen=1

[kitchen.panels.00.Satellite]
#auto_interval = 10  # seconds, how long to show this page before auto switching to next page
source = "satellite_animation"  # page source - page is defined in oca_monitor/pages/example.py
vertical_screen=1

[kitchen.panels.10.Weather]
#auto_interval = 10  # seconds, how long to show this page before auto switching to next page
source = "weather"  # page source - page is defined in oca_monitor/pages/example.py
vertical_screen = 1

#[kitchen.panels.20.Buttons]
#source = "buttons_kitchen"  # page source - page is defined in oca_monitor/pages/

[kitchen.panels.20.Buttons]
source = "buttons_message_screens"  # page source - page is defined in oca_monitor/pages/
light = 'kitchen'


##--------------------------screens tvroom---------------

[tvroom]  # global configuration is used by all environments, setting from here override all other settings
window_size = [1080, 1850]
panel_columns = [1]  # The size ratio of the columns in the panel grid
panel_rows = [6,3,2,1]   # The size ratio of the rows in the panel grid
style = "dark"
#style = "white"

nats_host = "nats.oca.lan"
nats_port = 4222

#log_level = "DEBUG"
log_level = "INFO"
#log_level = "WARNING"

# Panel page declaration:
# environment.panels.rowcolumn.tabname
[tvroom.panels.00.Allsky]
#auto_interval = 10  # seconds, how long to show this page before auto switching to next page
source = "allsky_animation"  # page source - page is defined in oca_monitor/pages/example.py
vertical_screen=1

[tvroom.panels.00.Satellite]
#auto_interval = 10  # seconds, how long to show this page before auto switching to next page
source = "satellite_animation"  # page source - page is defined in oca_monitor/pages/example.py
vertical_screen=1

[tvroom.panels.10.Weather]
#auto_interval = 10  # seconds, how long to show this page before auto switching to next page
source = "weather"  # page source - page is defined in oca_monitor/pages/example.py
vertical_screen = 1

[tvroom.panels.30.Telescopes]
source = "telescopes"  # page source - page is defined in oca_monitor/pages/example.py


[tvroom.panels.30.Buttons]
source = "buttons_message_screens"  # page source - page is defined in oca_monitor/pages/example.py
light='tvroom'

#----------dev----------

[dev]  # set OCAMONITOR_ENV=dev env var to use this configuration
nats_host = "localhost"

[dev.panels.00.wind]
source = "wind"

[dev.panels.00.hohohoh]
source = "example"
example_parameter = "Ho Ho"

