# All settings can be overriden by environment variables with the same name and prefix OCAMONITOR_
# e.g. OCAMONITOR_NATS_HOST=test.oca.lan

#---------------------------default - controlroom---------------------

[default]  # global configuration is used by all environments, setting from here override all other settings
window_size = [2400, 1200]
panel_columns = [7,3,1]  # The size ratio of the columns in the panel grid
panel_rows = [1]   # The size ratio of the rows in the panel grid
style = "dark"
#style = "white"

nats_host = "nats.oca.lan"
nats_port = 4222

#log_level = "DEBUG"
log_level = "INFO"
#log_level = "WARNING"

# Panel page declaration:
# environment.panels.rowcolumn.tabname
[default.panels.00.Allsky]
auto_interval = 10  # seconds, how long to show this page before auto switching to next page
source = "allsky"  # page source - page is defined in oca_monitor/pages/example.py
vertical_screen = "False"

[default.panels.01.Weather]
auto_interval = 10  # seconds, how long to show this page before auto switching to next page
source = "wind"  # page source - page is defined in oca_monitor/pages/example.py

[default.panels.02.Buttons]
auto_interval = 10  # seconds, how long to show this page before auto switching to next page
source = "buttons_screens"  # page source - page is defined in oca_monitor/pages/example.py

##--------------------------screens kitchen and salon---------------

[screen]  # global configuration is used by all environments, setting from here override all other settings
window_size = [1080, 1850]
panel_columns = [1]  # The size ratio of the columns in the panel grid
panel_rows = [7,4,1]   # The size ratio of the rows in the panel grid
style = "dark"
#style = "white"

nats_host = "nats.oca.lan"
nats_port = 4222

#log_level = "DEBUG"
log_level = "INFO"
#log_level = "WARNING"

# Panel page declaration:
# environment.panels.rowcolumn.tabname
[screen.panels.00.Allsky]
#auto_interval = 10  # seconds, how long to show this page before auto switching to next page
source = "allsky"  # page source - page is defined in oca_monitor/pages/example.py
vertical_screen="True"

[screen.panels.10.Weather]
#auto_interval = 10  # seconds, how long to show this page before auto switching to next page
source = "wind"  # page source - page is defined in oca_monitor/pages/example.py

[screen.panels.20.Buttons]
source = "buttons_screens"  # page source - page is defined in oca_monitor/pages/example.py


#----------dev----------

[dev]  # set OCAMONITOR_ENV=dev env var to use this configuration
nats_host = "localhost"

[dev.panels.00.wind]
source = "wind"

[dev.panels.00.hohohoh]
source = "example"
example_parameter = "Ho Ho"

